### ISSUE TITLE
评测集指标问题

### ISSUE THREAD

**Issue by daxiaoluo** [Hanlard/Bert-for-WebQA#3]
想问下最终在WebQA数据集上，dev数据的em和f1值大概是多少

**Comment by Hanlard** [comment]
您好，这个数据集我没做太多测试，我记得跑完结果和半个epoch差不多



---原始邮件---
发件人: "Tao Luo"<notifications@github.com&gt;
发送时间: 2020年7月29日(周三) 下午5:11
收件人: "Hanlard/Bert-for-WebQA"<Bert-for-WebQA@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Hanlard/Bert-for-WebQA] 评测集指标问题 (#3)




 
想问下最终在WebQA数据集上，dev数据的em和f1值大概是多少

**Comment by daxiaoluo** [comment]
你好，训练的时候需要对负样本做采样么？我目前没对数据做过多处理，训练出来在评测集上效果不好。不知道是否是训练的时候正负样本数据不平衡导致的

**Comment by Hanlard** [comment]
您好，我这里没有做任何数据的处理，就是一个简单的信息抽取模型，这个问题我没有深入研究过，主要是用来锻炼一下代码能力

---原始邮件---
发件人: "Tao Luo"<notifications@github.com&gt;
发送时间: 2020年8月4日(周二) 下午4:33
收件人: "Hanlard/Bert-for-WebQA"<Bert-for-WebQA@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Hanlard"<491377729@qq.com&gt;;
主题: Re: [Hanlard/Bert-for-WebQA] 评测集指标问题 (#3)




 
你好，训练的时候需要对负样本做采样么？我目前没对数据做过多处理，训练出来在评测集上效果不好。不知道是否是训练的时候正负样本数据不平衡导致的

**Comment by daxiaoluo** [comment]
> 您好，我这里没有做任何数据的处理，就是一个简单的信息抽取模型，这个问题我没有深入研究过，主要是用来锻炼一下代码能力
> […](#)
> ---原始邮件--- 发件人: "Tao Luo"<notifications@github.com&gt; 发送时间: 2020年8月4日(周二) 下午4:33 收件人: "Hanlard/Bert-for-WebQA"<Bert-for-WebQA@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Hanlard"<491377729@qq.com&gt;; 主题: Re: [Hanlard/Bert-for-WebQA] 评测集指标问题 (#3) 你好，训练的时候需要对负样本做采样么？我目前没对数据做过多处理，训练出来在评测集上效果不好。不知道是否是训练的时候正负样本数据不平衡导致的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，依然感谢^_^
